-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username character varying(40) NOT NULL UNIQUE,
    fullname character varying(217),
    password character varying(40),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone
);

ALTER TABLE users ALTER COLUMN deleted_at SET DEFAULT NULL;

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_pkey ON users(id int4_ops);
CREATE UNIQUE INDEX users_username_key ON users(username text_ops);

-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    id_user integer REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    content character varying(217) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX posts_pkey ON posts(id int4_ops);

